version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn build
  build-and-deploy:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          command: git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
      - run:
          command: git config --global user.name "$GH_NAME" > /dev/null 2>&1
      - run:
          command: yarn deploy
workflows:
  version: 2
  build:
    jobs:
      - build
      - build-and-deploy:
          filters:
            branches:
              only: master
